
NDefines.NCountry.BASE_MAX_COMMAND_POWER = 500
NDefines.NCountry.BASE_COMMAND_POWER_GAIN = 0.5

NDefines.NMilitary.MAX_ARMY_EXPERIENCE = 2000
NDefines.NMilitary.MAX_NAVY_EXPERIENCE = 2000
NDefines.NMilitary.MAX_AIR_EXPERIENCE = 2000